# Generated by Django 5.1.3 on 2024-12-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_remove_attender_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_time',
        ),
        migrations.AddField(
            model_name='attender',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
