# Generated by Django 5.1.3 on 2024-12-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attender',
            name='events',
        ),
    ]
