# Generated by Django 5.1.4 on 2024-12-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attender',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='attender',
            constraint=models.UniqueConstraint(fields=('name', 'surname'), name='unique_name_surname'),
        ),
    ]
