# Generated by Django 5.1.4 on 2025-01-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_alter_attender_code_attender_unique_name_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='attender',
            name='has_code',
            field=models.BooleanField(default=False),
        ),
    ]
