# Generated by Django 5.1.3 on 2024-12-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_remove_attendance_check_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attender',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
